name: Deploy from Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  # -------------------------
  # 중계서버 
  # -------------------------

  test:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - name: Check SSH
        shell: powershell
        run: |

          $sshConfig = "C:\action-runner\.ssh\config"

          Write-Host "Checking SSH connection to H200..."
          ssh -F $sshConfig -o BatchMode=yes -o ConnectTimeout=10 h200 "echo SSH_OK && whoami && hostname"

          if ($LASTEXITCODE -ne 0) {
            throw "SSH connection failed. Exit code: $LASTEXITCODE"
          }

          Write-Host "Checking Docker on H200..."

          ssh -o BatchMode=yes  -o ConnectTimeout=10  h200 "docker ps"

          if ($LASTEXITCODE -ne 0) {
            throw "Docker command failed. Exit code: $LASTEXITCODE"
          }

          Write-Host "SSH and Docker checks completed successfully."


  # -------------------------
  # CD
  # -------------------------

  deploy:

    needs: test
    runs-on: [self-hosted, Windows, X64]
    environment: production

    steps:
      - name: Deploy
        shell: powershell
        run: |

          $sshConfig = "C:\action-runner\.ssh\config"

          Write-Host "Deploying govfund_agent..."
